name: Deploy pgpool with master slaves cluster


on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:latest'
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        yum install ansible

    - name: run exporters playbook
      run: |
        ansible-playbook -i hosts/inventory.ini main.yml