name: Deploy LOG3 example

on:
  push:
    branches:
      - master

jobs:
  deploy-services:
    name: Deploy Services
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

  
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Check python3 version
        run: python3 --version

      - name: Install ansible with pip3
        run: |
          pip3 install ansible
          ansible --version | grep "python version"
